// ── Claude Chat Mobile 全景手册 · 全书结构唯一事实来源 ──────────────
// 源码：/Users/raylee/code/claude-chat-mobile（dev 分支）
// 产物：本目录（gh-pages worktree 的 docs-site/）
// 文档完备度：完备（结合 docs/hard-rules.md, architecture.md, testing.md 与最新代码重叙述）
module.exports = {
  title: 'Claude Chat Mobile',
  subtitle: '项目全景手册',
  tagline: '把本机 claude CLI 接到手机上',
  repo: 'claude-chat-mobile',
  version: '手册 v2.1 · dev@3f488861',
  parts: [
    {
      id: 'p0', label: '起点', icon: '◆',
      desc: '定位、阅读路线、手册怎么用。',
      pages: [
        { slug: 'index', title: '封面与导读', home: true, time: 5,
          lead: '一句话认识项目，看清这本手册怎么读。' },
        { slug: 'reading-guide', title: '阅读顺序指南', time: 8,
          lead: '主线通读、30 分钟速览、按角色切入。' },
      ],
    },
    {
      id: 'p1', label: '第一部分 · 认识项目', icon: '01',
      desc: '是什么、架构分层、职责边界。',
      pages: [
        { slug: 'overview', title: '项目总览', time: 10,
          lead: '定位、适用场景、技术栈与仓库形态。',
          src: ['README.md', 'CLAUDE.md', 'docs/hard-rules.md'] },
        { slug: 'architecture', title: '系统架构', time: 14,
          lead: '从手机 UI 到本机 CLI 的分层与数据路径。',
          src: ['docs/architecture.md', 'app/src/server/app.js', 'app/server.js'] },
        { slug: 'boundaries', title: '职责边界', time: 8,
          lead: '做什么、不做什么；与 CLI / 云 / SaaS 的分界。',
          src: ['README.md', 'docs/hard-rules.md', 'SECURITY.md'] },
      ],
    },
    {
      id: 'p2', label: '第二部分 · 演进历程', icon: '02',
      desc: '今天的架构从哪些决策长出来。',
      pages: [
        { slug: 'evolution', title: '架构演进主线', time: 12,
          lead: '同步引擎、单驾驶员、门禁、文档极简等关键阶段。',
          src: ['git log', 'CLAUDE.md', 'docs/hard-rules.md'] },
      ],
    },
    {
      id: 'p3', label: '第三部分 · 方法论', icon: '03',
      desc: '终端等价、安全纵深、契约与门禁。',
      pages: [
        { slug: 'terminal-parity', title: '终端等价性', time: 10,
          lead: 'CLI 有什么 Web 就有什么；权限与配置同源。',
          src: ['CLAUDE.md', 'docs/hard-rules.md', 'docs/display-contracts.md'] },
        { slug: 'security-model', title: '安全模型', time: 12,
          lead: '单用户、令牌是启动前提、按 Host 的鉴权分支、设备审批与两个边界。',
          src: ['README.md', 'app/src/auth/', 'docs/hard-rules.md'] },
        { slug: 'single-driver', title: '单驾驶员模型', time: 10,
          lead: 'Web 与 CLI 不可同时写同一会话；镜像只读追平。',
          src: ['docs/architecture.md', 'app/src/agent/cli-mirror-state.js', 'app/src/sessions/history.js'] },
        { slug: 'contracts-gates', title: '契约与工程门禁', time: 10,
          lead: '事件契约、import 边界、inventory、check 流水线。',
          src: ['tests/gates/', 'docs/testing.md'] },
        { slug: 'glossary', title: '术语表', time: 6,
          lead: 'instance、envelope、mirror、TOFU 等高频词。' },
      ],
    },
    {
      id: 'p4', label: '第四部分 · 核心实现', icon: '04',
      desc: '按模块拆解运行时能力。',
      pages: [
        { slug: 'runtime-assembly', title: '启动与组装根', time: 12,
          lead: 'server.js 薄入口与 app.js 组装根的启动时序。',
          src: ['app/server.js', 'app/src/server/app.js', 'app/src/ops/config-file.js'] },
        { slug: 'agent-session', title: 'AgentSession', time: 14,
          lead: '长驻 SDK query、权限闸、环形缓冲、中断与运行时切档。',
          src: ['app/src/agent/agent.js', 'app/src/agent/approval-storage.js'] },
        { slug: 'events-sync', title: '事件信封与同步', time: 12,
          lead: 'agent:event 信封、seq/epoch、sync:since、catch-up。',
          src: ['app/src/server/app.js', 'app/src/shared/protocol.js', 'docs/architecture.md'] },
        { slug: 'sessions-history', title: '会话与历史', time: 12,
          lead: '事实源分工、worktree、/rewind 与分叉、删除保护。',
          src: ['app/src/sessions/'] },
        { slug: 'auth-device', title: '鉴权与设备信赖', time: 12,
          lead: 'AUTH_TOKEN、CF Access、限速、设备指纹 TOFU。',
          src: ['app/src/auth/', 'app/src/server/http.js'] },
        { slug: 'files-upload', title: '文件与上传', time: 10,
          lead: '工作区白名单、三层路径闸、附件与预览。',
          src: ['app/src/files/'] },
        { slug: 'frontend-pwa', title: '前端与 PWA', time: 10,
          lead: 'app/public/ 分层、Socket 客户端、可安装 PWA。',
          src: ['app/public/'] },
        { slug: 'notify-status', title: '通知与状态栏', time: 10,
          lead: 'Web Push / ntfy、statusline 与 CLI bridge。',
          src: ['app/src/ops/notifications.js', 'app/src/ops/statusline.js'] },
      ],
    },
    {
      id: 'p5', label: '第五部分 · 数据与集成', icon: '05',
      desc: '状态落在哪、外部依赖是谁。',
      pages: [
        { slug: 'data-store', title: '数据全景', time: 12,
          lead: 'CCM_DATA_DIR、transcript、上传与忽略态文件。',
          src: ['docs/hard-rules.md', 'app/src/shared/data-dir.js', 'app/src/sessions/sessions.js'] },
        { slug: 'integrations', title: '外部集成', time: 10,
          lead: 'Agent SDK、claude CLI、Cloudflare、推送通道。',
          src: ['package.json', 'app/src/auth/cf-access.js'] },
      ],
    },
    {
      id: 'p6', label: '第六部分 · 部署与运维', icon: '06',
      desc: '本地最短路径与生产常驻。',
      pages: [
        { slug: 'quickstart', title: '快速开始', time: 10,
          lead: '安装、setup、doctor、局域网与临时隧道。',
          src: ['README.md', 'docs/getting-started.md', 'scripts/setup.js'] },
        { slug: 'production-deploy', title: '生产部署', time: 14,
          lead: '两条启动入口、公网入口选型、ACCESS_PROFILE 与 BIND_MODE。',
          src: ['docs/deployment.md', 'desktop/launchd/'] },
        { slug: 'ops-troubleshoot', title: '运维与排错', time: 12,
          lead: '按入口重启、看日志、两种体检、常见故障。',
          src: ['docs/deployment.md', 'scripts/doctor.js'] },
      ],
    },
    {
      id: 'p7', label: '第七部分 · 参考与规范', icon: '07',
      desc: '规范、契约清单、漂移。',
      pages: [
        { slug: 'project-rules', title: '项目规范', time: 10,
          lead: '分支纪律、门禁、worktree 约定、测试分层。',
          src: ['CLAUDE.md', 'docs/hard-rules.md', 'docs/testing.md'] },
        { slug: 'api-events', title: '事件与端点参考', time: 12,
          lead: '入向 socket 事件、agent:event 类型、HTTP 运维端点。',
          src: ['app/src/shared/protocol.js', 'tests/gates/agent-event-contract.js'] },
        { slug: 'env-reference', title: '环境变量参考', time: 10,
          lead: '从 ccm.config.json 与 env-schema 核对的配置表。',
          src: ['app/src/ops/env-schema.js', 'app/src/ops/config-file.js'] },
        { slug: 'drift', title: '漂移清单', time: 8,
          lead: '文档与代码不一致处，以代码为准。',
          src: ['docs/hard-rules.md', 'CLAUDE.md'] },
      ],
    },
  ],
};
