// ── 全书结构 + 阅读顺序的唯一事实来源 ──────────────────────────────
// claude-chat-mobile 项目全景手册
module.exports = {
  title: 'Claude Chat Mobile',
  subtitle: '项目全景手册',
  tagline: '把本机 Claude Code 接到手机上——终端等价性的完整实现',
  repo: 'Ike-li/claude-chat-mobile',
  version: '手册 v1.0',
  parts: [
    {
      id: 'p0', label: '起点', icon: '◆',
      desc: '先到这里，拿到全局视角与阅读路线。',
      pages: [
        { slug: 'index', title: '封面与导读', home: true, time: 5,
          lead: '一页看懂这个项目是什么、为谁做、怎么读这本手册。' },
        { slug: 'reading-guide', title: '阅读顺序指南', time: 8,
          lead: '三条阅读路线：速览（30 分钟）、完整通读（2–3 小时）、按角色切入。' },
      ],
    },
    {
      id: 'p1', label: '第一部分 · 认识项目', icon: '01',
      desc: '它是什么、为谁服务、整体架构如何。',
      pages: [
        { slug: 'overview', title: '项目总览', time: 10,
          lead: '定位、核心理念、技术栈一览。',
          src: ['README.md', 'CLAUDE.md', 'docs/capabilities.md'] },
        { slug: 'architecture', title: '系统架构总览', time: 14,
          lead: '三层架构、模块全景图、一条消息如何从手机流到 Claude 再回来。',
          src: ['docs/design.md', 'docs/interfaces.md'] },
        { slug: 'boundaries', title: '职责边界与非目标', time: 8,
          lead: '各模块如何分工，什么坚决不做、为什么。',
          src: ['docs/design.md §6'] },
      ],
    },
    {
      id: 'p2', label: '第二部分 · 演进历程', icon: '02',
      desc: '理解今天的架构，先看清它从哪里来。',
      pages: [
        { slug: 'evolution', title: '架构演进主线', time: 12,
          lead: '从本地 CLI 到公网移动端的逐层演进，关键决策点回顾。',
          src: ['git history', 'docs/design.md'] },
        { slug: 'versions', title: '版本里程碑', time: 8,
          lead: 'v1.0 到 v1.2.1 的关键变更与架构转折。',
          src: ['git history', 'git tags'] },
      ],
    },
    {
      id: 'p3', label: '第三部分 · 方法论', icon: '03',
      desc: '项目背后的设计哲学与安全思维。',
      pages: [
        { slug: 'terminal-equivalence', title: '终端等价性原则', time: 12,
          lead: '唯一的判据：终端里有什么，手机就该有什么——以及为什么它是上下界。',
          src: ['docs/design.md §0–§2'] },
        { slug: 'security-model', title: '安全模型与威胁矩阵', time: 14,
          lead: '11 条安全不变量、威胁矩阵、鉴权分层——把本机 shell 暴露到公网的完整防御。',
          src: ['docs/design.md §4'] },
        { slug: 'mobile-first', title: '移动端优先的设计约束', time: 8,
          lead: '会话碎片化、弱网、注意力非对称——四个终端没有的问题如何塑造了整个架构。',
          src: ['docs/design.md §3'] },
      ],
    },
    {
      id: 'p4', label: '第四部分 · 核心实现', icon: '04',
      desc: '逐个拆解系统的核心模块。',
      pages: [
        { slug: 'server', title: '服务端中枢：server.js', time: 14,
          lead: 'Express + Socket.IO 事件契约层——多实例编排、鉴权闸门、推送与通知。',
          src: ['server.js'] },
        { slug: 'agent-sdk', title: 'Agent 会话封装：agent.js', time: 14,
          lead: 'AgentSession 类——SDK query 包装、权限闸门、环形缓冲、后台任务跟踪。',
          src: ['agent.js'] },
        { slug: 'session-management', title: '会话管理：sessions.js + history.js', time: 12,
          lead: '元数据持久化与 CLI JSONL 历史读取——两个模块如何分工，为什么消息内容不存服务端。',
          src: ['sessions.js', 'history.js'] },
        { slug: 'frontend', title: '前端应用：public/', time: 14,
          lead: '单页 PWA 的完整剖析——事件驱动 UI、流式渲染、离线恢复、多实例路由。',
          src: ['public/index.html', 'public/js/app.js', 'public/js/logic.js'] },
        { slug: 'infrastructure', title: '基础设施模块一览', time: 12,
          lead: 'workdirs、uploads、devices、statusline、notifications、models-cache——六个支撑模块的职责与协作。',
          src: ['workdirs.js', 'uploads.js', 'devices.js', 'statusline.js', 'notifications.js', 'models-cache.js'] },
        { slug: 'security-modules', title: '安全与诊断模块', time: 10,
          lead: 'cf-access、file-security、file-preview、sanitizer、doctor-runtime、interaction-log——纵深防御的每一层。',
          src: ['cf-access.js', 'file-security.js', 'file-preview.js', 'sanitizer.js', 'doctor-runtime.js', 'interaction-log.js'] },
      ],
    },
    {
      id: 'p5', label: '第五部分 · 数据与集成', icon: '05',
      desc: '数据从哪来、存哪去、怎么流动、和谁对接。',
      pages: [
        { slug: 'event-system', title: '事件系统与契约', time: 12,
          lead: '24 类 agent:event 的完整清单、信封结构、seq/epoch 去重机制。',
          src: ['docs/event-contract.md', 'scripts/agent-event-contract.js'] },
        { slug: 'data-flow', title: '数据流全景', time: 10,
          lead: '一条用户消息的完整旅程——从手机输入到 Claude 回复、再到历史回显的每一步。',
          src: ['docs/interfaces.md'] },
        { slug: 'external-integrations', title: '外部集成', time: 10,
          lead: 'Cloudflare Access JWT、Cloudflare Tunnel、Web Push、ntfy——四个外部系统的对接方式。',
          src: ['docs/deployment.md', 'cf-access.js', 'notifications.js'] },
      ],
    },
    {
      id: 'p6', label: '第六部分 · 部署与运维', icon: '06',
      desc: '怎么把它跑起来、跑稳、出了问题怎么查。',
      pages: [
        { slug: 'quickstart', title: '快速开始', time: 10,
          lead: '从零到手机访问的最短路径：安装、配置、启动。',
          src: ['README.md'] },
        { slug: 'deployment', title: '生产部署', time: 12,
          lead: '常驻服务 + 固定域名 + 双因素——公网安全部署的完整配方。',
          src: ['docs/deployment.md', 'deploy/'] },
        { slug: 'operations', title: '运维与故障排查', time: 10,
          lead: '日常运维命令、常见故障诊断、日志解读。',
          src: ['docs/deployment.md'] },
        { slug: 'doctor', title: '配置自检与安全体检', time: 8,
          lead: 'doctor.js 启动前 10 项检查 + UI 内安全体检的完整清单。',
          src: ['scripts/doctor.js', 'doctor-runtime.js'] },
      ],
    },
    {
      id: 'p7', label: '第七部分 · 参考与规范', icon: '07',
      desc: '接口速查、开发约定、避坑指南。',
      pages: [
        { slug: 'api-reference', title: 'API 接口速查', time: 12,
          lead: 'HTTP 端点、Socket.IO 入向/出向事件、内部模块 API 的完整索引。',
          src: ['docs/interfaces.md'] },
        { slug: 'conventions', title: '项目规范与约定', time: 8,
          lead: '分支纪律、提交自检、文档极简原则、测试策略。',
          src: ['CLAUDE.md', 'docs/design.md §7'] },
        { slug: 'testing', title: '测试体系', time: 10,
          lead: '零 token 契约测试 + 真实 token 冒烟测试 + 可视化 E2E——三层测试策略。',
          src: ['test/', 'scripts/smoke-*.js', 'scripts/visual-e2e-runner.js'] },
        { slug: 'drift', title: '漂移清单', time: 8,
          lead: '文档与代码不一致的地方，接手必读。以代码为准。',
          src: ['代码与文档交叉核对'] },
      ],
    },
  ],
};
