import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { test } from 'node:test';
import { classifyRepositoryPath, renderRepositoryMap } from '../../scripts/repo-inventory.js';

test('final inventory rejects legacy roots and loose test files', () => {
  assert.equal(classifyRepositoryPath('agent.js'), null);
  assert.equal(classifyRepositoryPath('.agents/plan.md'), null);
  assert.equal(classifyRepositoryPath('specs/plan.md'), null);
  assert.equal(classifyRepositoryPath('tests/loose.test.mjs'), null);
});

test('docs/ 不再通配放行：新 .md 须显式登记，未登记的历史文档同样被拒', () => {
  // 一次性产物（审计报告/进度笔记/提案）落进 docs/ 应被 inventory:check 拒绝
  assert.equal(classifyRepositoryPath('docs/one-off-audit-2026-08-01.md'), null);
  assert.equal(classifyRepositoryPath('docs/new-proposal.md'), null);
  // 已随宣传层下线的文档不再登记，回流应被拒
  assert.equal(classifyRepositoryPath('docs/design.md'), null);
  assert.equal(classifyRepositoryPath('docs/index.html'), null);
  assert.equal(classifyRepositoryPath('docs/screenshots/01-stream.png'), null);
  // 现存长期文档与生成清单仍正常分类
  assert.equal(classifyRepositoryPath('docs/deployment.md')?.category, 'Documentation');
  assert.equal(classifyRepositoryPath('docs/repository-map.md')?.category, 'Generated documentation');
});

test('repository map records entry path and generation source for every file', () => {
  const rendered = renderRepositoryMap(['package-lock.json', 'server.js', 'src/server/app.js']);
  assert.match(rendered, /\| Path \| Category \| Purpose \| Entry or consumer \| Generated by \| Retention \|/);
  assert.match(rendered, /`package-lock\.json`[^\n]+`npm install`/);
  assert.match(rendered, /`server\.js`[^\n]+`node server\.js`/);
  assert.match(rendered, /`src\/server\/app\.js`[^\n]+Imported by the runtime/);
});

test('repository inventory classifies every tracked or unignored project file', () => {
  const result = spawnSync(
    process.execPath,
    ['scripts/repo-inventory.js', '--check'],
    { cwd: process.cwd(), encoding: 'utf8' },
  );

  assert.equal(
    result.status,
    0,
    `inventory check failed\nstdout:\n${result.stdout}\nstderr:\n${result.stderr}`,
  );
  assert.match(result.stdout, /repository inventory OK/);
});
