import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { test } from 'node:test';
import { classifyRepositoryPath, renderRepositoryMap } from '../../scripts/repo-inventory.js';

test('final inventory rejects legacy roots and loose test files', () => {
  assert.equal(classifyRepositoryPath('agent.js'), null);
  assert.equal(classifyRepositoryPath('.agents/plan.md'), null);
  assert.equal(classifyRepositoryPath('specs/plan.md'), null);
  assert.equal(classifyRepositoryPath('tests/loose.test.mjs'), null);
});

test('docs/ 不再通配放行：新 .md 须显式登记，未登记的历史文档同样被拒', () => {
  // 一次性产物（审计报告/进度笔记/提案）落进 docs/ 应被 inventory:check 拒绝
  assert.equal(classifyRepositoryPath('docs/one-off-audit-2026-08-01.md'), null);
  assert.equal(classifyRepositoryPath('docs/new-proposal.md'), null);
  // 已随宣传层下线的文档不再登记，回流应被拒
  assert.equal(classifyRepositoryPath('docs/design.md'), null);
  assert.equal(classifyRepositoryPath('docs/index.html'), null);
  assert.equal(classifyRepositoryPath('docs/screenshots/01-stream.png'), null);
  // 现存长期文档与生成清单仍正常分类
  assert.equal(classifyRepositoryPath('docs/deployment.md')?.category, 'Documentation');
  assert.equal(classifyRepositoryPath('docs/repository-map.md')?.category, 'Generated documentation');
});

test('repository map records entry path and generation source for every file', () => {
  const rendered = renderRepositoryMap(['package-lock.json', 'server.js', 'src/server/app.js']);
  assert.match(rendered, /\| Path \| Category \| Purpose \| Entry or consumer \| Generated by \| Retention \|/);
  assert.match(rendered, /`package-lock\.json`[^\n]+`npm install`/);
  assert.match(rendered, /`server\.js`[^\n]+`node server\.js`/);
  assert.match(rendered, /`src\/server\/app\.js`[^\n]+Imported by the runtime/);
});

// 本用例靠 `git ls-files` 取文件清单，因此【只在 git 能用时才有意义】。
// 隔离测试容器里 .git 是 worktree 指针文件、指向宿主机路径（gitdir: /Users/.../.git/worktrees/xxx），
// 容器里解析不到 → git 报 "not a git repository" → 用例失败。但那不是仓库清单出了问题，
// 是环境没有 git 视图；判成 fail 会让容器里的整轮测试红在一个与被测行为无关的事上。
// 从 tarball 解压跑测试也是同一情况。所以：git 不可用就 skip 并说清楚原因，别假装通过、也别误报失败。
const gitUsable = spawnSync('git', ['rev-parse', '--is-inside-work-tree'], {
  cwd: process.cwd(), encoding: 'utf8',
}).status === 0;

test('repository inventory classifies every tracked or unignored project file', {
  skip: gitUsable ? false : '本用例需要可用的 git 工作树（容器/tarball 环境下 git 视图不可用）',
}, () => {
  const result = spawnSync(
    process.execPath,
    ['scripts/repo-inventory.js', '--check'],
    { cwd: process.cwd(), encoding: 'utf8' },
  );

  assert.equal(
    result.status,
    0,
    `inventory check failed\nstdout:\n${result.stdout}\nstderr:\n${result.stderr}`,
  );
  assert.match(result.stdout, /repository inventory OK/);
});
