import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { test } from 'node:test';
import { classifyRepositoryPath, renderRepositoryMap } from '../../scripts/repo-inventory.js';

test('final inventory rejects legacy roots and loose test files', () => {
  assert.equal(classifyRepositoryPath('agent.js'), null);
  assert.equal(classifyRepositoryPath('.agents/plan.md'), null);
  assert.equal(classifyRepositoryPath('specs/plan.md'), null);
  assert.equal(classifyRepositoryPath('tests/loose.test.mjs'), null);
});

test('repository map records entry path and generation source for every file', () => {
  const rendered = renderRepositoryMap(['package-lock.json', 'server.js', 'src/server/app.js']);
  assert.match(rendered, /\| Path \| Category \| Purpose \| Entry or consumer \| Generated by \| Retention \|/);
  assert.match(rendered, /`package-lock\.json`[^\n]+`npm install`/);
  assert.match(rendered, /`server\.js`[^\n]+`node server\.js`/);
  assert.match(rendered, /`src\/server\/app\.js`[^\n]+Imported by the runtime/);
});

test('repository inventory classifies every tracked or unignored project file', () => {
  const result = spawnSync(
    process.execPath,
    ['scripts/repo-inventory.js', '--check'],
    { cwd: process.cwd(), encoding: 'utf8' },
  );

  assert.equal(
    result.status,
    0,
    `inventory check failed\nstdout:\n${result.stdout}\nstderr:\n${result.stderr}`,
  );
  assert.match(result.stdout, /repository inventory OK/);
});
